version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/tomcat/webapps
hooks:
  BeforeInstall:
    - location: /opt/script/stopserver.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /opt/script/startserver.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: /opt/script/validateserver.sh
