version: 0.0
os: linux
files:
  - source: /sample
    destination: /usr/share/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/stopserver.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/startserver.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validateserver.sh
